---
applications:
- name: app-name
  memory: 128M
  disk_quota: 1GB
  instances: 1
  buildpack: test-bp
  timeout: 500
  command: cmd
  stack: win2012r2
  services:
  - mysql
  - mssql
  hosts:
  - home
  domains:
  - app.example.com
  path: c:\path\to\app
  env: 
    env1: first
    env2: second